# Helper loaded by notebooks. Run notebooks from the project root.
source("./../R/00_dependencies.R")
source("./../R/defaults.R")
source("./../R/prepare_data.R")
source("./../R/tokenizer.R")
source("./../R/similarity.R")
source("./../R/features_char.R")
source("./../R/features_word.R")
source("./../R/features_function_words.R")
source("./../R/features_pos.R")
source("./../R/features_punctuation.R")
source("./../R/features_sentence.R")
source("./../R/features_lexical.R")
source("./../R/features_readability.R")
source("./../R/ensemble.R")
source("./../R/export.R")
