---
title: "Stylometry Ensemble Report"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE}
source("../R/00_dependencies.R")
source("../R/defaults.R")
source("../R/tokenizer.R")
source("../R/similarity.R")
source("../R/features_char.R")
source("../R/features_word.R")
source("../R/features_function_words.R")
source("../R/features_pos.R")
source("../R/features_punctuation.R")
source("../R/features_sentence.R")
source("../R/features_lexical.R")
source("../R/features_readability.R")
source("../R/ensemble.R")
```

## Load prepared documents

```{r}
section_docs <- readr::read_csv("../data/prepared/kjv_section_docs.csv", show_col_types = FALSE)
dplyr::glimpse(section_docs)
```

## Run ensemble

```{r}
config <- default_config()
result <- run_stylometry_ensemble(section_docs, config = config, k_neighbors = 5)
```

## Weights used

```{r}
data.frame(class = names(result$weights_used), weight = as.numeric(result$weights_used))
```

## Overall similarity

```{r}
round(result$overall_similarity, 3)
```

## Nearest neighbors

```{r}
result$nearest_neighbors
```

## Class-level similarity

```{r}
names(result$class_similarity)
```

```{r}
round(result$class_similarity$char, 3)
```
